- name: Développement web
  image: /assets/images/author-selfie.png
- name: Administration et maintenance web
  image: /assets/images/author-selfie.png
- name: Audits de sécurité
  image: /assets/images/author-selfie.png
- name: Diagnostic et résolution de pannes système
  image: /assets/images/author-selfie.png
